### PR TITLE
clean base template

### PR DESCRIPTION
**Pull request by akornor**
use url_for() to generate links to favicon and css instead of hard-coding

### CODE REVIEW

**Comment by f-prime** [comment]
Yeah, I got lazy. Merging.

**Comment by badmon** [comment]
we all get lazy -- was working on a similar thing before i saw your project
i would love to build it with you (more features to implement)

**Comment by badmon** [comment]
shoot me an email -- raymondakornor@gmail.com

**Comment by f-prime** [comment]
I would love to build this with you as well!  I'm actively working on this
so it would be great to bring someone else on board. I'll email you.

**Pull request merged**
